# Generated by Django 5.0.2 on 2024-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
