# Generated by Django 5.0.2 on 2024-02-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musician_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument_type',
            field=models.CharField(choices=[('Percussion', 'Percussion'), ('Guitar', 'Guitar'), ('Woodwind', 'Woodwind'), ('Keyboard', 'Keyboard')], max_length=50),
        ),
    ]
